dataloader_args:
  batch_size: 2
  drop_last: true
  num_workers: 4
  pin_memory: false
  prefetch_factor: 2

dataset_args:
  resample_rate: 16000
  sample_num_per_epoch: 0
  shuffle: true
  shuffle_args:
    shuffle_size: 2500
  chunk_len: 48000

enable_amp: false
exp_dir: exp/BSRNN
gpus: '0,1'
log_batch_interval: 100

loss: SI_SNR
loss_args: {}

model: BSRNN
model_args:
        sr: 16000
        win: 512
        stride: 128
        feature_dim: 128
        num_repeat: 6
        spk_emb_dim: 256
        spk_fuse_type: 'additive'
        use_spk_transform: False

model_init: null
num_avg: 10
num_epochs: 150

optimizer: Adam
optimizer_args:
  lr: 0.001
  weight_decay: 0.0001

save_epoch_interval: 1

scheduler: ExponentialDecrease
scheduler_args:
  final_lr: 2.5e-05
  initial_lr: 0.001
  warm_from_zero: false
  warm_up_epoch: 0

seed: 42
