data_type: shard

dataloader_args:
  batch_size: 4
  drop_last: true
  num_workers: 4
  pin_memory: false
  prefetch_factor: 2

dataset_args:
  resample_rate: 16000
  sample_num_per_epoch: 0
  shuffle: true
  shuffle_args:
    shuffle_size: 2500
  chunk_len: 48000

enable_amp: false
exp_dir: exp/ConvTasNet/
gpus: 0,1
log_batch_interval: 100

loss: SI_SNR
loss_args: {}

model: ConvTasNet
model_args:
    B: 128
    H: 512
    L: 16
    N: 512
    P: 3
    R: 3
    X: 8
    activate: relu
    causal: false
    norm: gLN
    spk_fuse_type: 'FiLM'
    use_spk_transform: False
    use_deep_enc: True
    use_deep_dec: True
model_init: null
num_avg: 5
num_epochs: 150

optimizer: Adam
optimizer_args:
  lr: 0.001
  weight_decay: 0.0001
save_epoch_interval: 5

scheduler: ExponentialDecrease
scheduler_args:
  final_lr: 2.5e-05
  initial_lr: 0.001
  warm_from_zero: False
  warm_up_epoch: 0

seed: 42
